# Generated by Django 3.1.5 on 2021-02-09 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationfile',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
